// Generated by Wrangler by running `wrangler types`

interface Env {
	PARTY_HOST: "localhost:1999" | "api.richicoder1.partykit.dev";
	CALLBACK_OVERRIDE: "api.subathon-goal-tracker.local.richi.dev" | "";
	ASSETS: Fetcher;
}
